name: "Build nuget package"
on:
  push:
    branches: 
      - master
jobs:
  BuildTestAndPush:
    name: "Build test and push"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.x
      - name: Use CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      - name: "Restore"
        run: dotnet restore ./src/LodeKennes.Extensions.Scaleway.SecretManager/
      - name: "Build"
        run: dotnet build --no-restore -c Release ./src/LodeKennes.Extensions.Scaleway.SecretManager
      - name: "Run tests"
        run: dotnet test -c Release ./test/LodeKennes.Extensions.Scaleway.Tests
